SHOW USER;

--Creacion del usuario con su contraseña
CREATE USER CURSO IDENTIFIED BY CURSO;

-- Permiso de conexión
GRANT CONNECT TO CURSO;

--Permiso varios
GRANT CREATE TABLE, CREATE SYNONYM, CREATE PUBLIC SYNONYM, DROP PUBLIC SYNONYM TO CURSO;
GRANT CREATE TRIGGER, CREATE SEQUENCE TO CURSO;
GRANT CREATE PROCEDURE, CREATE TYPE TO CURSO;
GRANT SELECT ANY DICTIONARY TO CURSO;

--CUOTA DE ESPACIO
ALTER USER CURSO QUOTA 100M ON USERS;
